services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Descont@0
      - N8N_HOST=n8n.pharmaprice.shop
      - N8N_PORT=5678
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - WEBHOOK_URL=https://n8n.pharmaprice.shop/
      - N8N_PROTOCOL=http
    expose:
      - "5678"
    volumes:
      - ./docker_data/n8n:/home/node/.n8n
    restart: always
    networks:
      - shared-net

volumes:
  n8n_data:

networks:
  shared-net:
    name: shared-net
    driver: bridge
